### ISSUE TITLE
T300 F1 wheel no display

### ISSUE THREAD

**Issue by les100** [cdemetriadis/Thrustmaster-T300-Steering-Wheel-Emulator#13]
Hi,
Thanks for your generosity in providing full details of your build. I am having a problem with not being able to display anything.
I have loaded the i2c demo from arduino ide and get the hello world. Loading your code i get nothing. I wondered if it had anything to do with the display on/off switch but cant see in your docs where this switch is connected. I even disconnected everything and just had the Display and nano connected and still nothing. Any help would be appreciated. Thanks,  Les

**Comment by les100** [comment]
Thanks but i managed to sort it out.

**Comment by eroyee** [comment]
@cdemetriadis I believe this issue was due to the OP not initialising the eeprom from t300_functions.ino? 

Not sure whether you have any (software) build instructions but maybe it's worth including information around this and/or an if statement in the main code that will inform the operator if the eeprom is empty?

Apologies for not being specifically helpful and offering explicit code/text around this, but I'm not a user of your system (or indeed any such thing) and would hesitate to give further input without experience of what I was talking about... ;-)

**Comment by les100** [comment]
@eroyee  Thanks for your suggestion,you were 100% correct,never had to do this before.A note to that effect would have been helpful.

**Comment by cdemetriadis** [comment]
@eroyee @les100 Sorry for not being responsive on this issue. I've not touched this code in a while. I'd be more than happy if any of you contributed directly to the projected and made a pull request.
